name: fitness
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Chart packages
  fl_chart: ^0.68.0
  
  # Progress bar packages
  simple_animation_progress_bar: ^1.0.2
  simple_circular_progress_bar: ^1.0.2
  
  # Dotted line package
  dotted_dashed_line: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/img/