name: fitness2
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
 
  
  simple_animation_progress_bar: ^1.0.0
  simple_circular_progress_bar: ^1.0.0
  dotted_dashed_line: ^0.0.3   # ← thêm dòng này
  fl_chart: ^1.0.0
  animated_toggle_switch: ^0.8.5
  readmore: ^3.0.0
  dotted_line: ^3.2.3
  calendar_agenda:
    path: dev_lib/calendar_agenda/
  intl: ^0.20.2
dependency_overrides: 
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
